// examples/vue/codefend-output/app.vue
<script setup>
import { ref, computed } from "vue";

/**
 * ref
 */
const Ox0 = ref("Hello World");

/**
 * computed
 */
const Ox1 = ref(5);
const Ox2 = computed(() => {
    return Ox1.value + 5;
});

/**
 * function
 */
function Ox3() {
    console.log("clicked");
}
</script>
<template>
    <div class="Ox4">
        {{ Ox2 }}
    </div>
    <div class="Ox5">
        {{ Ox0 }}
    </div>
    <button @click="Ox3">Click me!</button>
</template>
<style lang="css" scoped>
.Ox4 {
    color: red;
}

.Ox5 {
    color: blue;
}
</style>

// examples/angular/codefend-output/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  Ox2 = "Codefend";

  Ox1() {
    console.log("clicked!");
  }
}

<button class="Ox0" (click)="Ox1()">{{ Ox2 }}"></button>
